services:
  - type: web
    name: password-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: password-db
          property: connectionString

databases:
  - name: password-db
    databaseName: password_manager
    user: password_user
    plan: free 